services:
  barbell:
    image: ghcr.io/pandalanax/barbell-training:latest
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
